server:
  port: 8001
spring:
  profiles:
    active: dev
subscription:
  url: http://localhost:8000/subscribe
  channels: Account
event:
  receiver:
    url: http://localhost:8001/event
  publisher:
    url: http://localhost:8000/event