language: java
jdk:
  - oraclejdk8
#before_install:
#  - cd customer && chmod +x gradlew && gradle wrapper && cd ..
env:
  - TEST_DIR=customer
  - TEST_DIR=apigateway
  - TEST_DIR=messageservice
before_script:
  - cd $TEST_DIR && chmod +x gradlew
script:
  - ./gradlew check --info
before_cache:
  - rm -f $TEST_DIR/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $TEST_DIR/.gradle/caches/
    - $TEST_DIR/.gradle/wrapper/
notifications:
  email: false
#  slack: opchat:QiLB2Ww1XEfz5WHhoiZTQr0T#exjobb2016
