language: java
jdk:
  - oraclejdk8
#before_install:
#  - cd customer && chmod +x gradlew && gradle wrapper && cd ..
env:
  - TEST_DIR=customer
  - TEST_DIR=apigateway
  - TEST_DIR=messageservice
before_build:
  - cd $TEST_DIR
script:
  - gradle check
notifications:
  email: false
#  slack: opchat:QiLB2Ww1XEfz5WHhoiZTQr0T#exjobb2016
