language: java
jdk:
  - oraclejdk8
env:
  - DIR=customer/ SCRIPT=unit-tests.sh
  - DIR=apigateway/ SCRIPT=unit-tests.sh
  - DIR=messageservice/ SCRIPT=unit-tests.sh
script:
  - scripts/$SCRIPT
notifications:
  email: false
#  slack: opchat:QiLB2Ww1XEfz5WHhoiZTQr0T#exjobb2016
