language: java
jdk:
  - oraclejdk8
env:
  - DIR=customer/ SCRIPT=unit_tests.sh
  - DIR=apigateway/ SCRIPT=unit_tests.sh
  - DIR=messageservice/ SCRIPT=unit_tests.sh
before_script:
  - cd $DIR && chmod +x gradlew
script:
  - scripts/$SCRIPT
notifications:
  email: false
#  slack: opchat:QiLB2Ww1XEfz5WHhoiZTQr0T#exjobb2016
