server:
  port: 8003
spring:
  profiles:
    active: dev
subscription:
  url: http://localhost:8000/subscribe
  channels: Item
event:
  receiver:
    url: http://localhost:8003/event
  publisher:
    url: http://localhost:8000/event