server:
  port: 8010

subscription:
  url: http://localhost:8000/subscribe_all

url:
  apigateway:
    command: http://localhost:8002/command
    users: http://localhost:8002/command
  customer:
    users: http://localhost:8001/users
  marketplace:
    items: http://localhost:8003/most_popular_item

event:
  receiver:
    url: http://localhost:8010/event

mitigation:
  threshold:
    window:
      size: 20
      time: 5000  # ms
  disable:
    duration: 10  # s
  ratelimit:
    interval: 500 # ms
  importantuser:
    memberfor: 5  # s
    minspend: 10  # credits
  importantitem:
    duration: 1 # days

