server:
  port: 8010

subscription:
  url: http://localhost:8000/subscribe_all

url:
  apigateway:
    command: http://localhost:8002/command
    users: http://localhost:8002/command
  customer:
    users: http://localhost:8001/users

event:
  receiver:
    url: http://localhost:8010/event
